name: ci

on: ["push"]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.7.0
      - name: Docker login
        uses: docker/login-action@v2.1.0
        with:
          username: bite
          password: bite
